### ISSUE TITLE
multi-network dApp connections

### ISSUE THREAD

**Issue by greg-nagy** [tahowallet/extension#1604]
- Feature pitch: https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Dapp-Connections-Update_su0P4#_luLeR
- Design
  - [dApp connection window](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=5242%3A123793)
  - [Inside extension](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=5242%3A123793)
- Guiding RFB: https://github.com/tallycash/extension/blob/main/rfb/rfb-3-multinetwork-dapp-connections.md

# dApp permissions
- [ ] refactor redux slice 
  - from flat structure to nested [see RFB](https://github.com/tallycash/extension/blob/284945f64ef704aba24d849dfd773ad8bf9e2d52/rfb/rfb-3-multinetwork-dapp-connections.md#L54)
  - rename slice to simply `dapp-permissions` > `dapp`
  - rename `allowedPages` > `allowed`
- [x] update authorization.ts with chainID handling
  - validate that the `chainID` in the transaction payload has been granted permission for the dApp.
- [x] update the migration to add permission for the new network to create permissions for polygon 
- [x] update permission deletion logic to remove all granted permission for every chain on permission revoke.

# Current Connections
...

**Comment by greg-nagy** [comment]
- refactor redux slice 
  - from flat structure to nested [see RFB](https://github.com/tallycash/extension/blob/284945f64ef704aba24d849dfd773ad8bf9e2d52/rfb/rfb-3-multinetwork-dapp-connections.md#L54)
  - rename slice to simply `dapp-permissions` > `dapp`
  - ❌ blocked: handle multi network deletion

**Comment by 0xDaedalus** [comment]
confirmed - these are the two divergences (so far)

**Comment by Shadowfiend** [comment]
Closing as the important bits are very very done.
