### ISSUE TITLE
Incremental onboarding improvements

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#2025]
We are considering a major onboarding flow revamp. First, though, we'd like to explore an incremental design that uses the same flow, but makes use of a tab rather than a restrictive extension popup window.

The goals here are to
* stem immediate user pain
* prevent onboarding from being accidentally aborted by extension popup behavior
* prevent the need for "re-onboarding"
* minimize bugs related to an extension that hasn't yet been onboard, like the famous "It looks like you don't have any accounts, that's sad for a wallet!" screen :)
* use a feature flag for further user evaluation and a product decision

# Tasks

- [x] Adapt the current onboarding design to a responsive tab @VladUXUI 
- [x] #2026
- [x] Implement the new tab onboarding design behind a feature flag
- [x] Ensure the new tab onboarding design isn't susceptible to Halborn's [Demonic vulnerability](https://halborn.com/disclosures/demonic-vulnerability/), which recently impacted MetaMask, Coinbase Wallet, & Phantom.

**Comment by VladUXUI** [comment]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=12428%3A213365

Took a quick stab at a few screens. see how they would look on full screen without changing design/content too much.
hard to resist not changing a bunch of things, but it should be decent for our first iteration. If Hailey decided later that we should prioritise this, w'll do a bigger (not huge) redesign

The one screen that is not in the extension flow is the congrats screen.
This is a bit of an edit from our Ledger congrats screen, but i think it's important for this flow
![image](https://user-images.githubusercontent.com/80846886/186850808-a0ed57c0-942a-4a89-8fcc-cf6b9ea57898.png)

**Comment by mhluongo** [comment]
For those shortcuts, we should be able to detect the OS and only show the relevant one

**Comment by mhluongo** [comment]
@VladUXUI what do you think of this tweak to the last page?

![Add-Wallet-Ledger-Step4](https://user-images.githubusercontent.com/427505/188214749-785d9c37-db74-43a7-ab01-83af57dfd266.png)

**Comment by VladUXUI** [comment]
> @VladUXUI what do you think of this tweak to the last page?
> 
> ![Add-Wallet-Ledger-Step4](https://user-images.githubusercontent.com/427505/188214749-785d9c37-db74-43a7-ab01-83af57dfd266.png)

100% Looks awesome and easier to scan

**Comment by beemeeupnow** [comment]
Is this complete?
