### ISSUE TITLE
Custom Tokens

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/extension#3228]
Add ability for users to manually add tokens.
We need this functionality for chains that aren't supported by alchemy, as discovery based on tx history won't be available

## Tasks: 
- [x] Add button in settings and bottom of asset list
- [x] Add custom asset page
- [x] Add asset preview
- [x] Add tooltip for contract address
- [x] Add snackbar to confirm asset was added
- [x] Add error if contract address format is wrong
- [x] Add warning if asset couldn't be validated in the chain
- [x] Add notification if asset already exists

## Important notes: 
🔔 Assets should be added for all accounts
🔔 We need to check contracts in a database and automatically fill in Asset name and Decimals

## Preview
![image](https://user-images.githubusercontent.com/80846886/229846336-588aa0f0-4571-40c5-abce-eca2179b6a31.png)

## Figma
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=18107-358273

**Comment by hakeemullahjan** [comment]
Hey, I am a web3/frontend developer, I'd love to take this and will transfer these Figma designs into react code.
Please can you assign this issue to me?

**Comment by hakeemullahjan** [comment]
@jagodarybacka

**Comment by hakeemullahjan** [comment]
@hyphenized is it possible can I to take this?

**Comment by hyphenized** [comment]
> @hyphenized is it possible can I to take this?

Hey @hakeemullahjan, thank you so much for your enthusiasm and willingness to help out! We really appreciate it. However, this feature is next in our roadmap and has a high priority so we won't be able to have community contributors work on it at the moment. I encourage you to check some of the other available issues, this should help you get more familiar with the codebase and you might find something else that interests you as well.

**Comment by hyphenized** [comment]
Closed in #3261
